version: "3.8"

services:
  web:
    build: .
    container_name: mapgis_web
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8011:8000"
    volumes:
      - .:/app
